### ISSUE TITLE
Cant close more than one tab of the same plugin opened

### ISSUE THREAD

**Issue by 3ti65** [kiwidoggie/Rime#26]
Cant close more than one tab of the same plugin opened.
Also, any attempts of closing Rime completely after that will fail. 

If you cant reproduce it, i'll dump my /plugins here.

**Comment by kiwidoggie** [comment]
This will require a slight modification to how the plugin system works. I will update this when the work has been completed, but this should not affect plugins in a major way. 

**The Fix:**
I will be creating a unique identifier for each of the plugins when they are loaded (this identifier is not to be used/created by user and will be handled automatically) and closing/opening/events will all be identified by this identifier instead of by plugin name (which is the current process)

**Comment by kiwidoggie** [comment]
This has been fixed in 1.6.6395.1202 (not yet pushed)
